services:
  paddle-ocr-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    restart: unless-stopped
    tty: true
    shm_size: 8G  # Increased shared memory as per PaddlePaddle recommendation
